name: blower
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  volume_controller: ^2.0.6
  get_it:
  share_plus:
  flutter_svg: ^2.0.1
  audioplayers: ^3.0.1
  google_fonts: ^4.0.3
  syncfusion_flutter_gauges: ^20.4.49
  sound_generator: ^0.0.9
  yodo1mas: ^0.1.2
  connectivity_plus:

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
